apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-amp
spec:
  selector: {app: amp-enterprise}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
  type: {{ .Values.service.type }}
